# Generated by Django 4.2.6 on 2023-12-13 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='hiredtae',
        ),
    ]
